CREATE DATABASE Cooker;
GO

USE Cooker;
GO

CREATE TABLE [User] (
    UserId INT IDENTITY NOT NULL PRIMARY KEY,
    PostAmount INT NOT NULL DEFAULT 0,
    FavouriteAmount INT NOT NULL DEFAULT 0,
    Username VARCHAR(25) NOT NULL,
    ProfilePicture VARBINARY(MAX),
    CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
);

CREATE TABLE Post (
    PostId INT IDENTITY NOT NULL PRIMARY KEY,
    UserId INT NOT NULL,
    Title VARCHAR(50) NOT NULL,
    [Description] VARCHAR(255) NOT NULL,
    Ingridients VARCHAR(255) NOT NULL,
    Instructions VARCHAR(500) NOT NULL,
    FavouriteAmount INT NOT NULL,
    HeaderPicture VARBINARY(MAX),
    CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),

    FOREIGN KEY (UserId) REFERENCES [User](UserId)
);

CREATE TABLE Comment (
    CommentId INT IDENTITY NOT NULL PRIMARY KEY,
    UserId INT NOT NULL,
    PostId INT NOT NULL,
    Content VARCHAR(255) NOT NULL,
    LikeAmount INT NOT NULL,
	Edited BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),

    FOREIGN KEY (UserId) REFERENCES [User](UserId),
    FOREIGN KEY (PostId) REFERENCES Post(PostId)
);

CREATE TABLE Favourite (
    FavouriteId INT IDENTITY NOT NULL PRIMARY KEY,
    UserId INT NOT NULL,
    PostId INT NOT NULL,

    FOREIGN KEY (UserId) REFERENCES [User](UserId),
    FOREIGN KEY (PostId) REFERENCES Post(PostId)
);
